containers:
  - name: {{ .Chart.Name }}
    dev:
      gitUrl: {{ .Values.nocalhost.gitUrl }}
      image: ghcr.io/nocalhost/dev-container/node:latest
      shell: bash
      workDir: /home/nocalhost-dev
      command:
        run: [ "npm install && npm run dev" ]
        debug: [ "npm install && npm run dev" ]
      debug:
        language: "node"
        remoteDebugPort: 9009
      hotReload: false
      sync:
        type: send
        filePattern:
          - ./
        ignoreFilePattern:
          - ".git"
          - ".idea"
          - ".github"
          - "node_modules"
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: "0.1"
          memory: 256Mi
      persistentVolumeDirs: 
        - path: "/home/nocalhost-dev"
          capacity: "20Gi"

