# Default values for app1-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  nocalhost:
    enabled: false
nocalhost:
  gitUrl: "https://github.com/jack230230/app1-frontend"
  # default prefix is "{{ Release.Namespace }}."
  # example:
  # ingressURLPrefix: "dev."
  annotations:
    path: conf/nocalhost.yaml
# deployment env
env:
  - name: ENV_DOMAIN
    value: pgweb-53t9jl6x4.forkmain.cloud
  - name: ENV_NAME
    value: main
#   - name: "foo"
#     value: "bar"
replicaCount: 1
image:
  repository: ghcr.io/jack230230/app1-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"
imagePullSecrets:
  - name: pgweb
nameOverride: ""
fullnameOverride: "app1-frontend"
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: pgweb-53t9jl6x4.forkmain.cloud
      paths:
        - pathType: ImplementationSpecific
          path: /
  annotations: {}
  tls: []
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
